development:
  adapter: mysql
  encoding: utf8
  database: filepile_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: filepile_test
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: filepile
  username: root
  password: 
  socket: /tmp/mysql.sock